

#### Local Development
@baseUrl = http://localhost:3000
### Production (https://cse-341-project1-jujz.onrender.com/)
# @baseUrl = https://cse-341-project1-jujz.onrender.com

### Get all contacts
GET {{baseUrl}}/contacts HTTP/1.1

### Get contact by ID (replace with actual ID from database)
GET {{baseUrl}}/contacts/690673ba6d74c47c1a4139bc

### Create new contact

POST {{baseUrl}}/contacts
Content-Type: application/json

{
  {
  "_id": {
    "$oid": "690673ba6d74c47c1a4139bc"
  },
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@email.com",
  "favoriteColor": "blue",
  "birthday": "1995-03-15"
}
}

### Update contact (replace with actual ID)
PUT {{baseUrl}}/contacts/6906745d6d74c47c1a4139be
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith-Johnson",
  "email": "jane.johnson@example.com",
  "favoriteColor": "Purple",
  "birthday": "1995-05-20"
}

### Delete contact 
DELETE {{baseUrl}}/contacts/6906746e6d74c47c1a4139bf

### Access Swagger Documentation
GET {{baseUrl}}/api-docs